# Generated by Django 2.1.5 on 2019-03-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('capital', models.CharField(max_length=15)),
                ('about', models.CharField(max_length=1000)),
                ('flag', models.CharField(max_length=15)),
                ('p1image', models.CharField(max_length=15)),
                ('aboutp1', models.CharField(max_length=1000)),
                ('p2image', models.CharField(max_length=15)),
                ('aboutp2', models.CharField(max_length=1000)),
                ('p3image', models.CharField(max_length=15)),
                ('aboutp3', models.CharField(max_length=1000)),
                ('p4image', models.CharField(max_length=15)),
                ('aboutp4', models.CharField(max_length=1000)),
                ('p5image', models.CharField(max_length=15)),
                ('aboutp5', models.CharField(max_length=1000)),
                ('p6image', models.CharField(max_length=15)),
                ('aboutp6', models.CharField(max_length=1000)),
                ('p7image', models.CharField(max_length=15)),
                ('aboutp7', models.CharField(max_length=1000)),
                ('p8image', models.CharField(max_length=15)),
                ('aboutp8', models.CharField(max_length=1000)),
                ('p9image', models.CharField(max_length=15)),
                ('aboutp9', models.CharField(max_length=1000)),
                ('p10image', models.CharField(max_length=15)),
                ('aboutp10', models.CharField(max_length=1000)),
            ],
        ),
    ]
