# Generated by Django 2.1.5 on 2019-03-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190316_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cardimage',
            field=models.CharField(default='CardImage.jpg', max_length=15),
        ),
    ]
