# Generated by Django 2.1.5 on 2019-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190317_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p10name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p1name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p2name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p3name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p4name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p5name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p6name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p7name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='p8name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
