# Generated by Django 2.1.5 on 2019-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_season_wonder'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='Not Resolved', max_length=20),
        ),
    ]
